create table usuario (id bigint not null auto_increment, age integer not null, first_name varchar(255), last_name varchar(255), salary bigint, username varchar(255), primary key (id)) engine=InnoDB;

create table usuario (id int8 generated by default as identity, age int4 not null, first_name varchar(255), last_name varchar(255), salary int8, username varchar(255), primary key (id));
